branch-defaults:
  main:
    environment: tdd-env-7
environment-defaults:
  tdd-env-7:
    branch: null
    repository: null
global:
  application_name: tdd3
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
